#!/bin/bash

function md() {
    [ -d $1 ] || mkdir -p $1
}

function main() {
    md .ssh
    echo ssh-keygen -t rsa
    ssh-keygen -t rsa
}

main


# 動作確認
# ssh -T git@github.com

# パスフレーズ省略
# eval `ssh-agent`
# ssh-add  ~/.ssh/id_rsa
